apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "str-keycloak.fullname" . }}-pv
  labels:
    {{- include "str-keycloak.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /run/desktop/mnt/host/c/persistentVolume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
