apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "str-keycloak.fullname" . }}-psql-pv-claim
  labels:
    {{- include "str-keycloak.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M