apiVersion: v1
kind: Service
metadata:
  name: {{ include "str-keycloak.fullname" . }}-psql
  labels:
    {{- include "str-keycloak.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}    
spec:
  ports:
    - port: 5432
  selector:
    {{- include "str-keycloak.selectorLabels" . | nindent 4 }}
    tier: psql
  clusterIP: None