apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "str-keycloak.fullname" . }}-psql-secrets
  labels:
    {{- include "str-keycloak.labels" . | nindent 4 }}
data:
  dbName: {{ template "dbNameEnc" . }}
  dbUser: {{ template "dbUserEnc" . }}
  dbPassword: {{ template "dbPasswordEnc" . }}