apiVersion: v1
kind: Service
metadata:
  name: {{ include "str-keycloak.fullname" . }}
  labels:
    {{- include "str-keycloak.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "str-keycloak.selectorLabels" . | nindent 4 }}
